maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 50)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 50)
basic.pause(2000)
basic.pause(500)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 50)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 50)
basic.pause(500)
basic.pause(200)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 50)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 50)
basic.pause(2000)
basic.pause(500)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 50)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 50)
basic.forever(function () {
	
})
